server:
  port: 51920

spring:
  datasource:
    name: myBlog
    url: jdbc:mysql://localhost:3306/?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: 
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  ###Redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  ###RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis-plus:
  type-aliases-package: com.zbw.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: "rb_"
upload:
  uploadAuthorImg: "/tmp/myblog/authorImg/"
  fileUploadDic: "/tmp/myblog/upload/"
  sqlAuthorImg: "/authorImg/"
  fileSqlDic: "/upload/"

